In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
## Assume that the lib is installed
import sys
sys.path.append("../..")

## Load audio

In [3]:
import IPython.display as ipd
audio = "../audio/7143-88743-0029.flac"
print('Original audio:')
ipd.display(ipd.Audio(audio))

Original audio:


## Spiritlm tokenizers

In [4]:
from spiritlm.speech_tokenizer import spiritlm_base, spiritlm_expressive

2024-01-23 14:39:38 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX


### SpiritLM-BASE tokenizer

In [5]:
## Load the tokenizer
tokenizer_base = spiritlm_base()

2024-01-23 14:39:43 | INFO | spiritlm.speech_tokenizer.hubert.inference_hubert_model | HubertModel Config: HubertConfig(label_rate=50.0, extractor_mode='default', encoder_layers=12, encoder_embed_dim=768, encoder_ffn_embed_dim=3072, encoder_attention_heads=12, activation_fn='gelu', layer_type='transformer', dropout=0.1, attention_dropout=0.1, activation_dropout=0.0, encoder_layerdrop=0.05, dropout_input=0.1, dropout_features=0.1, final_dim=256, untie_final_proj=True, layer_norm_first=False, conv_feature_layers='[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 3', conv_bias=False, logit_temp=0.1, target_glu=False, feature_grad_mult=0.1, mask_length=10, mask_prob=0.8, mask_selection='static', mask_other=0.0, no_mask_overlap=False, mask_min_space=1, mask_channel_length=10, mask_channel_prob=0.0, mask_channel_selection='static', mask_channel_other=0.0, no_mask_channel_overlap=False, mask_channel_min_space=1, conv_pos=128, conv_pos_groups=16, conv_pos_batch_norm=True, latent_temp=[2.0, 0.5, 0

Loaded InferenceHubertModel from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/hubert_25hz/mhubert_base_25hz.pt'
Loaded RobustQuantizer from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/hubert_25hz/km500_L11_robust.pt'


2024-01-23 14:39:48 | INFO | spiritlm.speech_tokenizer.hifigan.hifigan_vocoder | HifiGAN: Duration Prediction = True - Multiple Speaker = True - Multiple Style = True


Removing weight norm...
Loaded CodeHiFiGAN checkpoint from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/hifigan_spirit_base/generator.pt'


In [6]:
## encode_units
print('SpiritLM-BASE: Encode audio into units (not deduplicated) \n', '-'*20)
units = tokenizer_base.encode_units(audio)
print(units)

## encode_string
print('\nSpiritLM-BASE: Encode audio into string (deduplicated and sorted units) \n', '-'*20)
string_tokens = tokenizer_base.encode_string(audio)
print(string_tokens)

## decode from units
print('\nSpiritLM-BASE: Decode back to audio from units (not deduplicated) \n', '-'*20)
resyn_wav = tokenizer_base.decode(units, speaker_id=2)
ipd.display(ipd.Audio(resyn_wav, rate=16000))

## decode from string
print('\nSpiritLM-BASE: Decode back to audio from string (deduplicated and sorted units) \n', '-'*20)
resyn_dedup_wav = tokenizer_base.decode(string_tokens, speaker_id=2)
ipd.display(ipd.Audio(resyn_dedup_wav, rate=16000))

SpiritLM-BASE: Encode audio into units (not deduplicated) 
 --------------------
{'audio': '/opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/ntuanh/Projects/speechtextlm/packages/spiritlm/examples/audio/7143-88743-0029.flac', 'hubert': '99 49 38 149 149 71 423 427 492 288 315 153 153 389 497 412 247 354 7 96 452 452 176 266 266 77 248 336 336 211 166 65 94 224 224 148 492 191 440 440 41 41 457 79 382 451 332 216 114 340 478 74 79 370 272 370 370 53 477 65 171 60 258 111 111 111 111 338 338 23 23 338 23 338 338 338 7 338 338 149 406 7 361 361 361 99 99 99 99 99 99 99 209 209 209 209 209 479 50 50 7 149 149 35 35 130 130 169 169 72 434 119 272 4 249 245 245 433 159 294 139 359 343 269 302 226 370 216 459 424 424 226 382 7 58 138 428 397 350 350 306 306 306 84 11 171 171 60 314 227 227 355 9 58 138 226 370 272 382 334 330 176 176 307 145 248 493 64 44 388 7 111 111 111 111 23 23 481 149 149 80 70 431 457 79 79 249 249 245 245 245 433 433 316 316 180 458 458 458 86 86 225 103 60 96 119 119 12


SpiritLM-BASE: Decode back to audio from string (deduplicated and sorted units) 
 --------------------


### SpiritLM-EXPRESSIVE Tokenizer

In [7]:
## Load the tokenizer
tokenizer_expressive = spiritlm_expressive()

2024-01-23 14:39:59 | INFO | fairseq.checkpoint_utils | load_model_ensemble_and_task is_moe=False


Using 'fcpe' f0 extractor method (choices are: ['pyaapt', 'fcpe'])
VQVAE model loaded from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/f0/f0interp_outfeats_norm_vuv2_l1loss_64bins_ds16/checkpoint_best.pt'!


2024-01-23 14:40:25 | INFO | fairseq.checkpoint_utils | Rank 0: Done reading from disk
2024-01-23 14:40:26 | INFO | fairseq.tasks.new_speech_decoder | dictionary size (dict.spm_nllb.txt): 256,206
2024-01-23 14:40:41 | INFO | fairseq.models.speech_decoder.new_speech_decoder | loaded sentence encoder /data/home/padqn/encoder_denoise_autoencode_reg2_100k.pt


Loading compression model from checkpoint: /data/home/padqn/encodec/encodec_25hz.th


2024-01-23 14:40:50 | INFO | fairseq.checkpoint_utils | Done loading state dict


Model sucessfully loaded from /fsx-ust/padqn/speech_decoder_cp/finetuning_1st_stage_v1/init_0.001_middle_crop/backup/checkpoint_3_33000.pt!
Loaded KmeansModel from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/speechprop_v2/km_100.pt'
Loaded Style Classifier from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/speechprop_v2/classifier_model.pt'


2024-01-23 14:40:53 | INFO | spiritlm.speech_tokenizer.hifigan.hifigan_vocoder | HifiGAN: Duration Prediction = True - Multiple Speaker = True - Multiple Style = False


Removing weight norm...
Loaded CodeHiFiGAN checkpoint from '/data/home/ntuanh/Projects/speechtextlm/packages/spiritlm/checkpoints/speech_tokenizer/hifigan_spirit_expressive/generator.pt'


In [8]:
## encode_units
print('SpiritLM-EXPRESSIVE: Encode audio into units (not deduplicated) \n', '-'*20)
units = tokenizer_expressive.encode_units(audio)
print(units)

## encode_string
print('\nSpiritLM-EXPRESSIVE: Encode audio into string (deduplicated and sorted units) \n', '-'*20)
string_tokens = tokenizer_expressive.encode_string(audio)
print(string_tokens)

## decode from units
print('\nSpiritLM-EXPRESSIVE: Decode back to audio from units (not deduplicated) \n', '-'*20)
resyn_wav = tokenizer_expressive.decode(units, speaker_id=2)
ipd.display(ipd.Audio(resyn_wav, rate=16000))

## decode from string
print('\nSpiritLM-EXPRESSIVE: Decode back to audio from string (deduplicated and sorted units) \n', '-'*20)
resyn_dedup_wav = tokenizer_expressive.decode(string_tokens, speaker_id=2)
ipd.display(ipd.Audio(resyn_dedup_wav, rate=16000))

SpiritLM-EXPRESSIVE: Encode audio into units (not deduplicated) 
 --------------------
{'audio': '/opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/ntuanh/Projects/speechtextlm/packages/spiritlm/examples/audio/7143-88743-0029.flac', 'hubert': '99 49 38 149 149 71 423 427 492 288 315 153 153 389 497 412 247 354 7 96 452 452 176 266 266 77 248 336 336 211 166 65 94 224 224 148 492 191 440 440 41 41 457 79 382 451 332 216 114 340 478 74 79 370 272 370 370 53 477 65 171 60 258 111 111 111 111 338 338 23 23 338 23 338 338 338 7 338 338 149 406 7 361 361 361 99 99 99 99 99 99 99 209 209 209 209 209 479 50 50 7 149 149 35 35 130 130 169 169 72 434 119 272 4 249 245 245 433 159 294 139 359 343 269 302 226 370 216 459 424 424 226 382 7 58 138 428 397 350 350 306 306 306 84 11 171 171 60 314 227 227 355 9 58 138 226 370 272 382 334 330 176 176 307 145 248 493 64 44 388 7 111 111 111 111 23 23 481 149 149 80 70 431 457 79 79 249 249 245 245 245 433 433 316 316 180 458 458 458 86 86 225 103 60 96 119 


SpiritLM-EXPRESSIVE: Decode back to audio from string (deduplicated and sorted units) 
 --------------------


## Test load each component

In [9]:
from spiritlm.speech_tokenizer.hubert import spirit_hubert
from spiritlm.speech_tokenizer.hifigan import spirit_base_hifigan, spirit_expressive_hifigan
from spiritlm.speech_tokenizer.f0 import spirit_expressive_f0
from spiritlm.speech_tokenizer.style_encoder import spirit_expressive_w2v2

In [ ]:
hubert = spirit_hubert()
pitcher = spirit_expressive_f0()
styler = spirit_expressive_w2v2()
voc = spirit_base_hifigan()
voc_ex = spirit_expressive_hifigan()

In [11]:
hubert(audio)

tensor([ 99,  49,  38, 149, 149,  71, 423, 427, 492, 288, 315, 153, 153, 389,
        497, 412, 247, 354,   7,  96, 452, 452, 176, 266, 266,  77, 248, 336,
        336, 211, 166,  65,  94, 224, 224, 148, 492, 191, 440, 440,  41,  41,
        457,  79, 382, 451, 332, 216, 114, 340, 478,  74,  79, 370, 272, 370,
        370,  53, 477,  65, 171,  60, 258, 111, 111, 111, 111, 338, 338,  23,
         23, 338,  23, 338, 338, 338,   7, 338, 338, 149, 406,   7, 361, 361,
        361,  99,  99,  99,  99,  99,  99,  99, 209, 209, 209, 209, 209, 479,
         50,  50,   7, 149, 149,  35,  35, 130, 130, 169, 169,  72, 434, 119,
        272,   4, 249, 245, 245, 433, 159, 294, 139, 359, 343, 269, 302, 226,
        370, 216, 459, 424, 424, 226, 382,   7,  58, 138, 428, 397, 350, 350,
        306, 306, 306,  84,  11, 171, 171,  60, 314, 227, 227, 355,   9,  58,
        138, 226, 370, 272, 382, 334, 330, 176, 176, 307, 145, 248, 493,  64,
         44, 388,   7, 111, 111, 111, 111,  23,  23, 481, 149, 1

In [12]:
wav = voc(hubert(audio), speaker_id=1).cpu().numpy()
ipd.Audio(wav, rate=16000)

In [13]:
pitcher(audio)

array([39, 57, 48, 48, 56, 44, 42, 59, 51, 44, 43,  0, 54, 13, 39, 25, 58,
       26, 44, 26, 13, 20, 46, 26, 26, 40, 26, 56, 51, 14, 46, 41, 41, 40,
       40, 39, 39, 39, 57, 57, 59, 59, 59, 59, 59, 20, 20, 20, 20, 35, 35,
       55, 13,  3, 52,  9,  9, 20, 57, 56, 56, 56, 56, 32, 39, 57, 46, 27,
       20, 44, 32, 59, 59, 42, 48, 48, 56, 44, 25, 56, 26, 56, 46, 56, 40,
       39, 39, 59, 59, 13, 15, 47, 13, 27, 55, 54, 36, 53,  3, 26, 43, 49,
        3, 39, 41, 14, 56, 46, 14, 46, 40, 40, 39, 40])

In [14]:
styler(audio)

tensor([71, 71, 71, 71, 71, 71, 71, 71, 71, 83], device='cuda:0')

In [15]:
wav_ex = voc_ex(
            code=hubert(audio),
            f0_code=pitcher(audio),
            style_code=styler(audio),
            dur_pred=False,
            speaker_id=1,
            not_dedup_code=True,
        ).cpu().numpy()
ipd.Audio(wav_ex, rate=16000)